"""NLP Fundamental in Tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gnG6K79et9WLTrlNE2C8Rle_29TCis8r

# Introduction to NLP Fundamentals in TensorFlow

NLP has the goal of deriving information out of natural language (could be sequences Text or speech). Another common term for NLP problems is sequence to sequence problems(seq2seq)

## check for GPU
"""

!nvidia-smi =L

"""##Get helper function"""

!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

# Import series of helper functions for the notebook

from helper_functions import unzip_data,create_tensorboard_callback,plot_loss_curves,compare_historys



"""## Get a text dataset 

The dataset we're going to be using is Kaggle's introduction to NLP dataset(text samples of Tweeets labelled as disaster or not disaster).

see the original source here: https://www.kaggle.com/competitions/nlp-getting-started/data
"""

!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

# Unzip data

unzip_data("nlp_getting_started.zip")